CREATE TABLE IF NOT EXISTS preliminary_staging(
as_of_year TEXT,
respondent_id TEXT,
agency_name TEXT,
agency_abbr TEXT,
agency_code TEXT,
loan_type_name TEXT,
loan_type TEXT,
property_type_name TEXT,
property_type TEXT,
loan_purpose_name TEXT,
loan_purpose TEXT,
owner_occupancy_name TEXT,
owner_occupancy TEXT,
loan_amount_000s TEXT,
preapproval_name TEXT,
preapproval TEXT,
action_taken_name TEXT,
action_taken TEXT,
msamd_name TEXT,
msamd TEXT,
state_name TEXT,
state_abbr TEXT,
state_code TEXT,
county_name TEXT,
county_code TEXT,
census_tract_number TEXT,
applicant_ethnicity_name TEXT,
applicant_ethnicity TEXT,
co_applicant_ethnicity_name TEXT,
co_applicant_ethnicity TEXT,
applicant_race_name_1 TEXT,
applicant_race_1 TEXT,
applicant_race_name_2 TEXT,
applicant_race_2 TEXT,
applicant_race_name_3 TEXT,
applicant_race_3 TEXT,
applicant_race_name_4 TEXT,
applicant_race_4 TEXT,
applicant_race_name_5 TEXT,
applicant_race_5 TEXT,
co_applicant_race_name_1 TEXT,
co_applicant_race_1 TEXT,
co_applicant_race_name_2 TEXT,
co_applicant_race_2 TEXT,
co_applicant_race_name_3 TEXT,
co_applicant_race_3 TEXT,
co_applicant_race_name_4 TEXT,
co_applicant_race_4 TEXT,
co_applicant_race_name_5 TEXT,
co_applicant_race_5 TEXT,
applicant_sex_name TEXT,
applicant_sex TEXT,
co_applicant_sex_name TEXT,
co_applicant_sex TEXT,
applicant_income_000s TEXT,
purchaser_type_name TEXT,
purchaser_type TEXT,
denial_reason_name_1 TEXT,
denial_reason_1 TEXT,
denial_reason_name_2 TEXT,
denial_reason_2 TEXT,
denial_reason_name_3 TEXT,
denial_reason_3 TEXT,
rate_spread TEXT,
hoepa_status_name TEXT,
hoepa_status TEXT,
lien_status_name TEXT,
lien_status TEXT,
edit_status_name TEXT,
edit_status TEXT,
sequence_number TEXT,
population TEXT,
minority_population TEXT,
hud_median_family_income TEXT,
tract_to_msamd_income TEXT,
number_of_owner_occupied_units TEXT,
number_of_1_to_4_family_units TEXT,
applications_date_indicator TEXT
);


\copy preliminary_staging FROM 'CSV PATH' WITH DELIMITER ',' CSV HEADER;



CREATE TABLE IF NOT EXISTS preliminary(as_of_year INTEGER,
respondent_id TEXT,
agency_name TEXT,
agency_abbr TEXT,
agency_code INTEGER,
loan_type_name TEXT,
loan_type INTEGER,
property_type_name TEXT,
property_type INTEGER,
loan_purpose_name TEXT,
loan_purpose INTEGER,
owner_occupancy_name TEXT,
owner_occupancy INTEGER,
loan_amount_000s INTEGER,
preapproval_name TEXT,
preapproval INTEGER,
action_taken_name TEXT,
action_taken INTEGER,
msamd_name TEXT,
msamd INTEGER,
state_name TEXT,
state_abbr TEXT,
state_code INTEGER,
county_name TEXT,
county_code INTEGER,
census_tract_number DOUBLE PRECISION,
applicant_ethnicity_name TEXT,
applicant_ethnicity INTEGER,
co_applicant_ethnicity_name TEXT,
co_applicant_ethnicity INTEGER,
applicant_race_name_1 TEXT,
applicant_race_1 INTEGER,
applicant_race_name_2 TEXT,
applicant_race_2 INTEGER,
applicant_race_name_3 TEXT,
applicant_race_3 INTEGER,
applicant_race_name_4 TEXT,
applicant_race_4 INTEGER,
applicant_race_name_5 TEXT,
applicant_race_5 INTEGER,
co_applicant_race_name_1 TEXT,
co_applicant_race_1 INTEGER,
co_applicant_race_name_2 TEXT,
co_applicant_race_2 INTEGER,
co_applicant_race_name_3 TEXT,
co_applicant_race_3 INTEGER,
co_applicant_race_name_4 TEXT,
co_applicant_race_4 INTEGER,
co_applicant_race_name_5 TEXT,
co_applicant_race_5 INTEGER,
applicant_sex_name TEXT,
applicant_sex INTEGER,
co_applicant_sex_name TEXT,
co_applicant_sex INTEGER,
applicant_income_000s INTEGER,
purchaser_type_name TEXT,
purchaser_type INTEGER,
denial_reason_name_1 TEXT,
denial_reason_1 INTEGER,
denial_reason_name_2 TEXT,
denial_reason_2 INTEGER,
denial_reason_name_3 TEXT,
denial_reason_3 INTEGER,
rate_spread TEXT,
hoepa_status_name TEXT,
hoepa_status INTEGER,
lien_status_name TEXT,
lien_status INTEGER,
edit_status_name TEXT,
edit_status INTEGER,
sequence_number TEXT,
population INTEGER,
minority_population DOUBLE PRECISION,
hud_median_family_income INTEGER,
tract_to_msamd_income DOUBLE PRECISION,
number_of_owner_occupied_units INTEGER,
number_of_1_to_4_family_units INTEGER,
applications_date_indicator TEXT,
id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY
);





INSERT INTO preliminary (
  as_of_year,
  respondent_id,
  agency_name,
  agency_abbr,
  agency_code,
  loan_type_name,
  loan_type,
  property_type_name,
  property_type,
  loan_purpose_name,
  loan_purpose,
  owner_occupancy_name,
  owner_occupancy,
  loan_amount_000s,
  preapproval_name,
  preapproval,
  action_taken_name,
  action_taken,
  msamd_name,
  msamd,
  state_name,
  state_abbr,
  state_code,
  county_name,
  county_code,
  census_tract_number,
  applicant_ethnicity_name,
  applicant_ethnicity,
  co_applicant_ethnicity_name,
  co_applicant_ethnicity,
  applicant_race_name_1,
  applicant_race_1,
  applicant_race_name_2,
  applicant_race_2,
  applicant_race_name_3,
  applicant_race_3,
  applicant_race_name_4,
  applicant_race_4,
  applicant_race_name_5,
  applicant_race_5,
  co_applicant_race_name_1,
  co_applicant_race_1,
  co_applicant_race_name_2,
  co_applicant_race_2,
  co_applicant_race_name_3,
  co_applicant_race_3,
  co_applicant_race_name_4,
  co_applicant_race_4,
  co_applicant_race_name_5,
  co_applicant_race_5,
  applicant_sex_name,
  applicant_sex,
  co_applicant_sex_name,
  co_applicant_sex,
  applicant_income_000s,
  purchaser_type_name,
  purchaser_type,
  denial_reason_name_1,
  denial_reason_1,
  denial_reason_name_2,
  denial_reason_2,
  denial_reason_name_3,
  denial_reason_3,
  rate_spread,
  hoepa_status_name,
  hoepa_status,
  lien_status_name,
  lien_status,
  edit_status_name,
  edit_status,
  sequence_number,
  population,
  minority_population,
  hud_median_family_income,
  tract_to_msamd_income,
  number_of_owner_occupied_units,
  number_of_1_to_4_family_units,
  applications_date_indicator
)
SELECT
  NULLIF(as_of_year, '')::INTEGER,
  respondent_id,
  agency_name,
  agency_abbr,
  NULLIF(agency_code, '')::INTEGER,
  loan_type_name,
  NULLIF(loan_type, '')::INTEGER,
  property_type_name,
  NULLIF(property_type, '')::INTEGER,
  loan_purpose_name,
  NULLIF(loan_purpose, '')::INTEGER,
  owner_occupancy_name,
  NULLIF(owner_occupancy, '')::INTEGER,
  NULLIF(loan_amount_000s, '')::INTEGER,
  preapproval_name,
  NULLIF(preapproval, '')::INTEGER,
  action_taken_name,
  NULLIF(action_taken, '')::INTEGER,
  msamd_name,
  NULLIF(msamd, '')::INTEGER,
  state_name,
  state_abbr,
  NULLIF(state_code, '')::INTEGER,
  county_name,
  NULLIF(county_code, '')::INTEGER,
  NULLIF(census_tract_number, '')::DOUBLE PRECISION,
  applicant_ethnicity_name,
  NULLIF(applicant_ethnicity, '')::INTEGER,
  co_applicant_ethnicity_name,
  NULLIF(co_applicant_ethnicity, '')::INTEGER,
  applicant_race_name_1,
  NULLIF(applicant_race_1, '')::INTEGER,
  applicant_race_name_2,
  NULLIF(applicant_race_2, '')::INTEGER,
  applicant_race_name_3,
  NULLIF(applicant_race_3, '')::INTEGER,
  applicant_race_name_4,
  NULLIF(applicant_race_4, '')::INTEGER,
  applicant_race_name_5,
  NULLIF(applicant_race_5, '')::INTEGER,
  co_applicant_race_name_1,
  NULLIF(co_applicant_race_1, '')::INTEGER,
  co_applicant_race_name_2,
  NULLIF(co_applicant_race_2, '')::INTEGER,
  co_applicant_race_name_3,
  NULLIF(co_applicant_race_3, '')::INTEGER,
  co_applicant_race_name_4,
  NULLIF(co_applicant_race_4, '')::INTEGER,
  co_applicant_race_name_5,
  NULLIF(co_applicant_race_5, '')::INTEGER,
  applicant_sex_name,
  NULLIF(applicant_sex, '')::INTEGER,
  co_applicant_sex_name,
  NULLIF(co_applicant_sex, '')::INTEGER,
  NULLIF(applicant_income_000s, '')::INTEGER,
  purchaser_type_name,
  NULLIF(purchaser_type, '')::INTEGER,
  denial_reason_name_1,
  NULLIF(denial_reason_1, '')::INTEGER,
  denial_reason_name_2,
  NULLIF(denial_reason_2, '')::INTEGER,
  denial_reason_name_3,
  NULLIF(denial_reason_3, '')::INTEGER,
  rate_spread,
  hoepa_status_name,
  NULLIF(hoepa_status, '')::INTEGER,
  lien_status_name,
  NULLIF(lien_status, '')::INTEGER,
  edit_status_name,
  NULLIF(edit_status, '')::INTEGER,
  sequence_number,
  NULLIF(population, '')::INTEGER,
  NULLIF(minority_population, '')::DOUBLE PRECISION,
  NULLIF(hud_median_family_income, '')::INTEGER,
  NULLIF(tract_to_msamd_income, '')::DOUBLE PRECISION,
  NULLIF(number_of_owner_occupied_units, '')::INTEGER,
  NULLIF(number_of_1_to_4_family_units, '')::INTEGER,
  applications_date_indicator
FROM preliminary_staging;
